; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/cu.usbmodem11301
upload_protocol = esptool
upload_speed = 921600
upload_flags = --no-stub
monitor_port = /dev/cu.usbmodem11301
monitor_speed = 115200
build_flags =
	-DLV_CONF_INCLUDE_SIMPLE
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DUSER_SETUP_LOADED
	-DUSE_FSPI_PORT
	-DGC9D01_DRIVER
	-DTFT_WIDTH=160
	-DTFT_HEIGHT=160
	-DTFT_MOSI=14
	-DTFT_SCLK=13
	-DTFT_CS=12
	-DTFT_DC=11
	-DTFT_RST=10
	-DTFT_BL=9
	-DTFT_BACKLIGHT_ON=HIGH
	-DTFT_RGB_ORDER=1
	-DTFT_INVERSION_OFF
	-DLOAD_GLCD
	-DLOAD_FONT2
	-DLOAD_FONT4
	-DLOAD_FONT6
	-DLOAD_FONT7
	-DLOAD_FONT8
	-DLOAD_GFXFF
	-DSMOOTH_FONT
	-DSPI_FREQUENCY=27000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000
lib_deps =
	lvgl/lvgl@^9.5.0
